{-# OPTIONS --safe --without-K #-}
-- Generated by refl-check-levels --emit-world-modules; do not edit.
module Refl.World.Addition where

open import Refl.Nat
open import Refl.Eq
open import Refl.World.Tutorial using (zero-+)
open ≡-Reasoning

-- suc-+
suc-+ : ∀ (x y : ℕ) → suc x + y ≡ suc (x + y)

suc-+ x zero = refl
suc-+ x (suc y) = cong suc (suc-+ x y)


-- +-comm
+-comm : ∀ (x y : ℕ) → x + y ≡ y + x

+-comm x zero = sym (zero-+ x)
+-comm x (suc y) = trans (cong suc (+-comm x y)) (sym (suc-+ y x))


-- +-assoc
+-assoc : ∀ (x y z : ℕ) → (x + y) + z ≡ x + (y + z)

+-assoc x y zero = refl
+-assoc x y (suc z) = cong suc (+-assoc x y z)


-- +-right-comm and ≡-Reasoning
+-right-comm : ∀ (x y z : ℕ) → (x + y) + z ≡ (x + z) + y

+-right-comm x y z =
  begin
    (x + y) + z ≡⟨ +-assoc x y z ⟩
    x + (y + z) ≡⟨ cong (x +_) (+-comm y z) ⟩
    x + (z + y) ≡⟨ sym (+-assoc x z y) ⟩
    (x + z) + y ∎


-- +-swap
+-swap : ∀ (x y z : ℕ) → x + (y + z) ≡ y + (x + z)

+-swap x y z =
  begin
    x + (y + z) ≡⟨ sym (+-assoc x y z) ⟩
    (x + y) + z ≡⟨ cong (_+ z) (+-comm x y) ⟩
    (y + x) + z ≡⟨ +-assoc y x z ⟩
    y + (x + z) ∎


-- suc is injective
pred : ℕ → ℕ
pred zero = zero
pred (suc n) = n

suc-injective : ∀ {x y : ℕ} → suc x ≡ suc y → x ≡ y

suc-injective h = cong pred h


-- +-cancelʳ
+-cancelʳ : ∀ (x y z : ℕ) → x + z ≡ y + z → x ≡ y

+-cancelʳ x y zero h = h
+-cancelʳ x y (suc z) h = +-cancelʳ x y z (suc-injective h)


-- Reading: a finite sum
sumTo : (ℕ → ℕ) → ℕ → ℕ
sumTo f zero = zero
sumTo f (suc n) = sumTo f n + f n

sumTo-zero : ∀ (n : ℕ) → sumTo (λ _ → zero) n ≡ zero

sumTo-zero zero = refl
sumTo-zero (suc n) = sumTo-zero n

