{-# OPTIONS --safe --without-K #-}
-- Generated by refl-check-levels --emit-world-modules; do not edit.
module Refl.World.Equality where

open import Refl.Nat
open import Refl.Eq
open import Refl.Logic
open import Refl.Bool
open import Refl.World.Logic using (_≟_)
open ≡-Reasoning

-- Pattern matching on refl is J
J : ∀ {A : Set} {x : A} (P : ∀ y → x ≡ y → Set) → P x refl → ∀ {y} (p : x ≡ y) → P y p

J P d refl = d


-- Function equality and ≗
cong-app : ∀ {A B : Set} {f g : A → B} → f ≡ g → ∀ x → f x ≡ g x

infix 4 _≗_
_≗_ : ∀ {A B : Set} → (A → B) → (A → B) → Set
f ≗ g = ∀ x → f x ≡ g x

≗-trans : ∀ {A B : Set} {f g h : A → B} → f ≗ g → g ≗ h → f ≗ h

cong-app refl x = refl

≗-trans p q x = trans (p x) (q x)


-- with abstraction
δ : ℕ → ℕ → ℕ
δ i j with i ≟ j
... | yes _ = 1
... | no  _ = 0

δ-diag : ∀ (i : ℕ) → δ i i ≡ 1

δ-diag i with i ≟ i
... | yes _ = refl
... | no ¬p = ⊥-elim (¬p refl)


-- with … in eq
f : ℕ → ℕ
f n with n ≡ᵇ 0
... | true  = 1
... | false = n

f-nonzero : ∀ (n : ℕ) → n ≢ 0 → f n ≡ n

f-nonzero n h with n ≡ᵇ 0 in eq
... | true  = ⊥-elim (h (≡ᵇ⇒≡ n 0 eq))
... | false = refl


-- The old inspect idiom
g : ℕ → ℕ
g n with n ≡ᵇ 0
... | true  = 1
... | false = n

record Reveal_·_is_ {A B : Set} (g : A → B) (x : A) (y : B) : Set where
  constructor [_]
  field eq : g x ≡ y

inspect : ∀ {A B : Set} (g : A → B) (x : A) → Reveal g · x is g x
inspect g x = [ refl ]

g-nonzero : ∀ (n : ℕ) → n ≢ 0 → g n ≡ n

g-nonzero n h with n ≡ᵇ 0 | inspect (n ≡ᵇ_) 0
... | true  | [ eq ] = ⊥-elim (h (≡ᵇ⇒≡ n 0 eq))
... | false | _ = refl


-- Rewrite chains
two-three : ∀ (x y : ℕ) → x ≡ 2 → y ≡ 3 → x + y ≡ 5

two-three x y p q rewrite p | q = refl


-- Pattern-matching lambdas
sym′ : ∀ {A : Set} {x y : A} → x ≡ y → y ≡ x

sym′ = λ { refl → refl }


-- subst and transport
trans′ : ∀ {x y z : ℕ} → x ≡ y → y ≡ z → x ≡ z

trans′ {x} p q = subst (x ≡_) q p


-- Hedberg: decidable equality gives UIP
canon : ∀ {x y : ℕ} → x ≡ y → x ≡ y
canon {x} {y} p with x ≟ y
... | yes q = q
... | no ¬q = ⊥-elim (¬q p)

canon-const : ∀ {x y : ℕ} (p q : x ≡ y) → canon p ≡ canon q
canon-const {x} {y} p q with x ≟ y
... | yes _ = refl
... | no ¬q = ⊥-elim (¬q p)

trans-symˡ : ∀ {A : Set} {x y : A} (e : x ≡ y) → trans (sym e) e ≡ refl

canon-inv : ∀ {x y : ℕ} (p : x ≡ y) → trans (sym (canon refl)) (canon p) ≡ p

≡-irrelevant : ∀ {x y : ℕ} (p q : x ≡ y) → p ≡ q

trans-symˡ refl = refl

canon-inv refl = trans-symˡ (canon refl)

≡-irrelevant p q =
  begin
    p                                    ≡⟨ sym (canon-inv p) ⟩
    trans (sym (canon refl)) (canon p)   ≡⟨ cong (trans (sym (canon refl))) (canon-const p q) ⟩
    trans (sym (canon refl)) (canon q)   ≡⟨ canon-inv q ⟩
    q                                    ∎


-- Reading: δ is symmetric (Matrix.lagda)
δ-sym : ∀ (i j : ℕ) → δ i j ≡ δ j i

δ-sym i j with i ≟ j | j ≟ i
... | yes _ | yes _ = refl
... | yes p | no ¬q = ⊥-elim (¬q (sym p))
... | no ¬p | yes q = ⊥-elim (¬p (sym q))
... | no _  | no _  = refl

