{-# OPTIONS --safe --without-K #-}
-- Generated by refl-check-levels --emit-world-modules; do not edit.
module Refl.World.Logic where

open import Refl.Nat
open import Refl.Eq
open import Refl.Logic

-- Implication is a function
modus-ponens : ∀ {A B : Set} → A → (A → B) → B

modus-ponens a f = f a


-- And is a pair
×-comm : ∀ {A B : Set} → A × B → B × A

×-comm (a , b) = b , a


-- Or is a choice
⊎-comm : ∀ {A B : Set} → A ⊎ B → B ⊎ A

⊎-comm (inj₁ a) = inj₂ a
⊎-comm (inj₂ b) = inj₁ b


-- From falsity, anything
ex-falso : ∀ {A : Set} → ⊥ → A

trivial : ⊤

ex-falso ()

trivial = tt


-- Negation is a function to ⊥
contraposition : ∀ {A B : Set} → (A → B) → ¬ B → ¬ A

contraposition f ¬b a = ¬b (f a)


-- For all
∀-× : ∀ {P Q : ℕ → Set} → (∀ n → P n × Q n) → (∀ n → P n) × (∀ n → Q n)

∀-× h = (λ n → proj₁ (h n)) , (λ n → proj₂ (h n))


-- There exists
witness : ∃ (λ n → n + 1 ≡ 3)

witness = 2 , refl


-- Decidable equality
map-suc : ∀ {m n : ℕ} → Dec (m ≡ n) → Dec (suc m ≡ suc n)
map-suc (yes p) = yes (cong suc p)
map-suc (no ¬p) = no (λ { refl → ¬p refl })

infix 4 _≟_
_≟_ : (m n : ℕ) → Dec (m ≡ n)

zero ≟ zero = yes refl
zero ≟ suc n = no (λ ())
suc m ≟ zero = no (λ ())
suc m ≟ suc n = map-suc (m ≟ n)


-- If and only if
×-swap-⇔ : ∀ {A B : Set} → (A × B) ⇔ (B × A)

×-swap-⇔ = mk⇔ ×-comm ×-comm


-- Reading: languages as predicates
Pred : Set₁
Pred = ℕ → Set

infixr 6 _∪_
infixr 7 _∩_

_∪_ : Pred → Pred → Pred
(P ∪ Q) n = P n ⊎ Q n

_∩_ : Pred → Pred → Pred
(P ∩ Q) n = P n × Q n

∩⊆∪ : ∀ (P Q : Pred) (n : ℕ) → (P ∩ Q) n → (P ∪ Q) n

∩⊆∪ P Q n (p , _) = inj₁ p

