{-# OPTIONS --safe --without-K #-}
-- Generated by refl-check-levels --emit-world-modules; do not edit.
module Refl.World.Multiplication where

open import Refl.Nat
open import Refl.Eq
open import Refl.World.Tutorial using (zero-+)
open import Refl.World.Addition using (+-comm; +-assoc; +-right-comm; +-swap)
open ≡-Reasoning

-- *-one
*-one : ∀ (x : ℕ) → x * 1 ≡ x

*-one x = zero-+ x


-- zero-*
zero-* : ∀ (x : ℕ) → zero * x ≡ zero

zero-* zero = refl
zero-* (suc x) = zero-* x


-- suc-*
suc-* : ∀ (x y : ℕ) → suc x * y ≡ x * y + y

suc-* x zero = refl
suc-* x (suc y) = cong suc
  (begin
    suc x * y + x ≡⟨ cong (_+ x) (suc-* x y) ⟩
    x * y + y + x ≡⟨ +-right-comm (x * y) y x ⟩
    x * y + x + y ∎)


-- *-comm
*-comm : ∀ (x y : ℕ) → x * y ≡ y * x

*-comm x zero = sym (zero-* x)
*-comm x (suc y) = trans (cong (_+ x) (*-comm x y)) (sym (suc-* y x))


-- one-*
one-* : ∀ (x : ℕ) → 1 * x ≡ x

one-* x = trans (*-comm 1 x) (*-one x)


-- *-distribˡ-+
*-distribˡ-+ : ∀ (x y z : ℕ) → x * (y + z) ≡ x * y + x * z

*-distribˡ-+ x y zero = refl
*-distribˡ-+ x y (suc z) = trans (cong (_+ x) (*-distribˡ-+ x y z)) (+-assoc (x * y) (x * z) x)


-- *-assoc
*-assoc : ∀ (x y z : ℕ) → (x * y) * z ≡ x * (y * z)

*-assoc x y zero = refl
*-assoc x y (suc z) = trans (cong (_+ x * y) (*-assoc x y z)) (sym (*-distribˡ-+ x (y * z) y))


-- x ^ 2
^-two : ∀ (x : ℕ) → x ^ 2 ≡ x * x

^-two x = cong (_* x) (one-* x)


-- Reading: a factor out of a sum
sumTo : (ℕ → ℕ) → ℕ → ℕ
sumTo f zero = zero
sumTo f (suc n) = sumTo f n + f n

sum-factor : ∀ (c : ℕ) (f : ℕ → ℕ) (n : ℕ) → sumTo (λ i → c * f i) n ≡ c * sumTo f n

sum-factor c f zero = refl
sum-factor c f (suc n) = trans (cong (_+ c * f n) (sum-factor c f n)) (sym (*-distribˡ-+ c (sumTo f n) (f n)))

