{-# OPTIONS --safe --without-K #-}
-- Generated by refl-check-levels --emit-world-modules; do not edit.
module Refl.World.Tutorial where

open import Refl.Nat
open import Refl.Eq
open ≡-Reasoning

-- Meet in the middle
two-plus-two-by-hand : 2 + 2 ≡ 4

two-plus-two-by-hand =
  begin
    2 + 2        ≡⟨⟩
    suc (suc 2)  ≡⟨⟩
    suc 3        ≡⟨⟩
    4            ∎


-- refl
two-plus-two : 2 + 2 ≡ 4

two-plus-two = refl


-- A variable in the way
same : ∀ (x : ℕ) → x ≡ x

same x = refl


-- cong
suc-cong : ∀ {x y : ℕ} → x ≡ y → suc x ≡ suc y

suc-cong h = cong suc h


-- rewrite
use-h : ∀ (x : ℕ) → x ≡ 3 → x + 2 ≡ 5

use-h x h rewrite h = refl


-- Refine and Normalise
three-steps : ∀ (x : ℕ) → (x + 2) + 1 ≡ x + 3

three-steps x = refl


-- Case split is induction
zero-+ : ∀ (x : ℕ) → zero + x ≡ x

zero-+ zero = refl
zero-+ (suc x) = cong suc (zero-+ x)


-- sym and trans
flip-chain : ∀ {x y z : ℕ} → y ≡ x → y ≡ z → x ≡ z

flip-chain p q = trans (sym p) q


-- Reading: analog₁ (Timely Computation)
analog₁ : ℕ → (ℕ → ℕ) → (ℕ → ℕ) → (ℕ → ℕ)
analog₁ δ h x̃ = λ t → h (x̃ (t + δ))

analog₁′ : ℕ → (ℕ → ℕ) → (ℕ → ℕ) → (ℕ → ℕ)

analog-same : ∀ δ h x̃ t → analog₁ δ h x̃ t ≡ analog₁′ δ h x̃ t

analog₁′ δ h x̃ t = h (x̃ (t + δ))

analog-same δ h x̃ t = refl

