-- | Content CI: every level × language must (a) accept its model solution as
-- Solved and (b) leave its template Unsolved with no errors. Also generates
-- the per-world Agda support modules from the level sources.
module Refl.Check
  ( Outcome (..)
  , checkGame
  , emitWorldModules
  , worldModuleName
  , renderWorldModule
  ) where

import           Control.Exception      (SomeException, try)
import           Control.Monad          (forM)
import           Data.Char              (toUpper)
import           Data.List              (nub)
import qualified Data.Map               as M
import           Data.Text              (Text)
import qualified Data.Text              as T
import qualified Data.Text.IO           as TIO
import           System.Directory       (createDirectoryIfMissing)
import           System.FilePath        ((</>))

import           Refl.Content
import           Refl.Language
import           Refl.Language.Registry
import           Refl.Protocol.Types

data Outcome = Outcome
  { oWorld :: Text
  , oLevel :: Text
  , oLang  :: Text
  , oOk    :: Bool
  , oNotes :: [Text]
  } deriving (Show)

checkGame :: Env -> Maybe LangId -> LoadedGame -> IO [Outcome]
checkGame env only game = fmap concat . forM (lgWorlds game) $ \w ->
  fmap concat . forM (lwLevels w) $ \l ->
    forM [ s | (lang, s) <- M.toList (llSources l), maybe True (== lang) only ] $ \src ->
      checkLevel env (wmId (lwMeta w)) (lmId (llMeta l)) src

checkLevel :: Env -> Text -> Text -> LevelSources -> IO Outcome
checkLevel env world level src = do
  let lang = lsLang src
      out ok notes = Outcome world level (unLangId lang) ok notes
  case lookupLanguage lang of
    Nothing -> pure (out False ["unknown language"])
    Just l | not (liAvailable (langInfo l)) -> pure (out True ["skipped: language unavailable"])
    Just l -> do
      r <- try (langStart l env src)
      case r of
        Left (e :: SomeException) -> pure (out False ["could not start prover: " <> T.pack (show e)])
        Right (Left e) -> pure (out False ["could not start prover: " <> e])
        Right (Right prover) -> do
          sol <- psCheck prover (lsSolution src)
          tpl <- psCheck prover (lsTemplate src)
          psClose prover
          let solNotes = case crVerdict sol of
                Solved -> []
                v -> ["solution is not Solved: " <> T.pack (show v) <> "; " <> crStatus sol]
                     ++ map diagMessage (crDiagnostics sol)
              tplNotes = case crVerdict tpl of
                Unsolved n | n > 0 -> []
                Solved -> ["template is already solved"]
                v -> ["template does not load cleanly: " <> T.pack (show v) <> "; " <> crStatus tpl]
                     ++ map diagMessage (crDiagnostics tpl)
              notes = solNotes ++ tplNotes
          pure (out (null notes) notes)

-- ---------------------------------------------------------------------------
-- World support modules (Agda)
-- ---------------------------------------------------------------------------

-- | @tutorial@ → @Tutorial@, @multiplication-power@ → @MultiplicationPower@.
worldModuleName :: Text -> Text
worldModuleName = T.concat . map cap . T.splitOn "-"
 where
  cap t = case T.unpack t of
    [] -> ""
    (c : cs) -> T.pack (toUpper c : cs)

-- | One module per world with an Agda source: the union of the levels'
-- prelude lines (minus OPTIONS, module headers and self-imports) followed by
-- every statement and model solution, so later levels can @open import@ them.
renderWorldModule :: LoadedWorld -> Maybe Text
renderWorldModule w
  | null srcs = Nothing
  | otherwise = Just $ T.unlines $
      [ "{-# OPTIONS " <> T.unwords opts <> " #-}"
      , "-- Generated by refl-check-levels --emit-world-modules; do not edit."
      , "module Refl.World." <> modName <> " where"
      , "" ]
      ++ imports
      ++ concat
        [ [ "", "-- " <> lmTitle (llMeta l), lsStatement s, lsSolution s ]
        | (l, s) <- srcs ]
 where
  modName = worldModuleName (wmId (lwMeta w))
  opts = case M.lookup "agda" (wmOptions (lwMeta w)) of
    Just os | not (null os) -> os
    _ -> ["--safe", "--without-K"]
  srcs = [ (l, s) | l <- lwLevels w, Just s <- [M.lookup (LangId "agda") (llSources l)] ]
  imports = nub
    [ line
    | (_, s) <- srcs
    , line <- T.lines (T.take (T.length (lsPrefix s) - T.length (lsStatement s)) (lsPrefix s))
    , not (T.null (T.strip line))
    , not ("{-#" `T.isPrefixOf` T.strip line)
    , not ("module " `T.isPrefixOf` T.strip line)
    , not (("Refl.World." <> modName) `T.isInfixOf` line)
    ]

emitWorldModules :: LoadedGame -> FilePath -> IO [FilePath]
emitWorldModules game dir = do
  createDirectoryIfMissing True (dir </> "Refl" </> "World")
  fmap concat . forM (lgWorlds game) $ \w ->
    case renderWorldModule w of
      Nothing -> pure []
      Just src -> do
        let path = dir </> "Refl" </> "World" </> T.unpack (worldModuleName (wmId (lwMeta w))) ++ ".agda"
        TIO.writeFile path src
        pure [path]
