-- | Extract agda-mode's unicode input translations from @agda-input.el@ and
-- render them as a Haskell module for the frontend.
--
-- The table in agda-input.el is an elisp alist; three entry shapes cover
-- essentially all of it:
--
-- > ("to" . ("→"))
-- > ("r" . ("→" "⇒" "↝"))
-- > ("Gr" . ,(agda-input-to-string-list "αβγ…"))
module Refl.InputTable
  ( parseAgdaInputEl
  , renderInputModule
  , extraTranslations
  ) where

import           Data.Char (isSpace)
import           Data.List (sortOn)
import qualified Data.Map  as M
import           Data.Text (Text)
import qualified Data.Text as T

-- | Sequences agda-input inherits from Emacs's TeX input method, which is
-- not shipped with Agda; the ones people actually type.
extraTranslations :: [(Text, [Text])]
extraTranslations =
  [ ("alpha", ["α"]), ("beta", ["β"]), ("gamma", ["γ"]), ("delta", ["δ"]), ("epsilon", ["ε"])
  , ("zeta", ["ζ"]), ("eta", ["η"]), ("theta", ["θ"]), ("iota", ["ι"]), ("kappa", ["κ"])
  , ("lambda", ["λ"]), ("mu", ["μ"]), ("nu", ["ν"]), ("xi", ["ξ"]), ("pi", ["π"]), ("rho", ["ρ"])
  , ("sigma", ["σ"]), ("tau", ["τ"]), ("phi", ["φ"]), ("chi", ["χ"]), ("psi", ["ψ"]), ("omega", ["ω"])
  , ("Gamma", ["Γ"]), ("Delta", ["Δ"]), ("Theta", ["Θ"]), ("Lambda", ["Λ"]), ("Pi", ["Π"])
  , ("Sigma", ["Σ"]), ("Phi", ["Φ"]), ("Psi", ["Ψ"]), ("Omega", ["Ω"])
  , ("forall", ["∀"]), ("exists", ["∃"]), ("neg", ["¬"]), ("top", ["⊤"]), ("bot", ["⊥"])
  , ("times", ["×"]), ("circ", ["∘"]), ("cdot", ["·"]), ("equiv", ["≡"]), ("ne", ["≠"])
  , ("le", ["≤"]), ("ge", ["≥"]), ("in", ["∈"]), ("notin", ["∉"]), ("cup", ["∪"]), ("cap", ["∩"])
  , ("subseteq", ["⊆"]), ("langle", ["⟨"]), ("rangle", ["⟩"]), ("ldots", ["…"]), ("infty", ["∞"])
  , ("to", ["→"]), ("rightarrow", ["→"]), ("leftarrow", ["←"]), ("Rightarrow", ["⇒"]), ("Leftarrow", ["⇐"])
  , ("mapsto", ["↦"]), ("iff", ["⇔"]), ("wedge", ["∧"]), ("vee", ["∨"]), ("oplus", ["⊕"]), ("otimes", ["⊗"])
  , ("_1", ["₁"]), ("_2", ["₂"]), ("_3", ["₃"]), ("^1", ["¹"]), ("^2", ["²"]), ("^l", ["ˡ"]), ("^r", ["ʳ"])
  , ("bN", ["ℕ"]), ("bZ", ["ℤ"]), ("bQ", ["ℚ"]), ("bR", ["ℝ"]), ("bB", ["𝔹"])
  , ("==", ["≡"]), ("=n", ["≠"]), ("<=", ["≤"]), (">=", ["≥"]), ("->", ["→"]), ("<-", ["←"]), ("=>", ["⇒"])
  , ("all", ["∀"]), ("ex", ["∃"]), ("Gl", ["λ"]), ("GL", ["Λ"]), ("Gs", ["σ"]), ("GS", ["Σ"]), ("Gd", ["δ"]), ("Gn", ["ν"])
  , ("::", ["∷"]), ("<>", ["⋄"]), ("o", ["∘"]), ("::", ["∷"]), ("qed", ["∎"]), ("[[", ["⟦"]), ("]]", ["⟧"])
  , ("((", ["⦅"]), ("))", ["⦆"]), ("{{", ["⦃"]), ("}}", ["⦄"]), ("<", ["⟨"]), (">", ["⟩"])
  , ("star", ["★"]), ("st", ["⋆"]), ("sq", ["□"]), ("diamond", ["◇"]), ("nabla", ["∇"]), ("emptyset", ["∅"])
  , ("bu", ["•"]), ("x", ["×"]), ("|-", ["⊢"]), ("|=", ["⊨"]), ("=~", ["≅"]), ("~", ["∼"]), ("~~", ["≈"])
  , ("'", ["′"]), ("''", ["″"]), ("_i", ["ᵢ"]), ("_j", ["ⱼ"]), ("_a", ["ₐ"]), ("_o", ["ₒ"]), ("^o", ["ᵒ"]), ("^m", ["ᵐ"])
  , ("Mc", ["𝒞"]), ("MD", ["𝒟"]), ("MU", ["𝒰"]), ("McL", ["ℒ"]), ("MiP", ["𝑃"]), ("bT", ["𝕋"]), ("bS", ["𝕊"])
  ]

-- | @(sequence, translations)@ pairs found in the elisp source.
parseAgdaInputEl :: Text -> [(Text, [Text])]
parseAgdaInputEl src = concatMap entry (T.splitOn "(\"" src)
 where
  entry chunk = case T.breakOn "\"" chunk of
    (key, rest)
      | T.null rest || T.null key -> []
      | otherwise ->
          let after = T.drop 1 rest
          in case T.stripPrefix " ." (T.dropWhile isSpace after) of
               Nothing -> []
               Just body ->
                 let b = T.dropWhile isSpace body
                 in if "(" `T.isPrefixOf` b then [(key, strings (T.takeWhile (/= ')') (T.drop 1 b)))]
                    else if ",(agda-input-to-string-list" `T.isPrefixOf` b
                      then case T.breakOn "\"" b of
                             (_, r) | T.null r -> []
                                    | otherwise -> [(key, map T.singleton (T.unpack (T.takeWhile (/= '"') (T.drop 1 r))))]
                      else []
  strings t = [ s | s <- T.splitOn "\"" t, not (T.null (T.strip s)), not (T.all isSpace s), s /= " " ]

-- | The Haskell module: a sorted association list; the frontend builds a
-- prefix map from it at startup.
renderInputModule :: [(Text, [Text])] -> Text
renderInputModule entries = T.unlines $
  [ "-- | Unicode input translations (agda-mode's \\ input method)."
  , "-- Generated by refl-gen-input-table; do not edit."
  , "module Widgets.InputTable (agdaTable) where"
  , ""
  , "import Data.Text (Text)"
  , ""
  , "agdaTable :: [(Text, [Text])]"
  , "agdaTable ="
  ] ++ zipWith row ("  [ " : repeat "  , ") (sortOn fst (M.toList merged)) ++ ["  ]"]
 where
  merged = M.fromListWith (\new old -> old ++ filter (`notElem` old) new)
             (filter (not . null . snd) (map clean (entries ++ extraTranslations)))
  clean (k, vs) = (k, filter (not . T.null) (map (T.filter (/= '"')) vs))
  row lead (k, vs) = lead <> "(" <> showT k <> ", [" <> T.intercalate ", " (map showT vs) <> "])"
  showT t = "\"" <> T.concatMap esc t <> "\""
  esc '\\' = "\\\\"
  esc '"'  = "\\\""
  esc c    = T.singleton c
